### ISSUE TITLE
eventemitter can only ve default-imported using the esModuleInterop flag

### ISSUE THREAD

**Issue by fabian-emilius** [sindresorhus/p-queue#146]
I recently got the error after upgrading from 6.6.2 to 7.1.0:

```
node_modules/p-queue/dist/index.d.ts:1:8 - error TS1259: Module '"..../node_modules/eventemitter3/index"' can only be default-imported using the 'esModuleInterop' flag
```

I think this line has to be changed to `import * as EventEmitter from 'eventemitter3'`
https://github.com/sindresorhus/p-queue/blob/76b81cd707a6cd31b41f25e5d7fa8abc7486c4bf/source/index.ts#L1

**Comment by simllll** [comment]
Related issue on my side: I cannot use .on().. as it says on is not a defined method, I guess because it cannot find the corret import of eventemitter

**Comment by AhmedToInfinity** [comment]
This is still an issue. Please update the import to `import * as EventEmitter from 'eventemitter3'`

```
Module '"node_modules/eventemitter3/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flagts(1259)

index.d.ts(134, 1): This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

This is because node_modules\eventemitter3\index.d.ts does _not_ have a default export.

Thank you.
